### ISSUE TITLE
Non-English characters are converted  to `?` in code generation

### ISSUE THREAD

**Issue by steve02081504** [brandoncomputer/powershell-designer#7]
Considering that my project reads fbs files directly, this bug doesn't affect me, so take your time.

Testuse fbs:
https://github.com/steve02081504/ps12exe/blob/master/src/locale/zh-CN.fbs

Reproduce the method:
Click on generate code

**Comment by brandoncomputer** [comment]
Assigned

**Comment by brandoncomputer** [comment]
Changed from ASCII to UTF8
